name = "infinex-multichain"
version = "0.0.14"
preset = "O2"
description = "Infinex MultiChain Deployments"
# --chain-id 421614 

[setting.OWNER]
defaultValue = "0x33FaF56Cb2c854231bdA8De328bbAddcF76D9836"
description = "The Council multisig"

[setting.ACCOUNT_TYPE]
description = "The code for a account type"
defaultValue = "0" # does not include trading module
 
[setting.WITHDRAWAL_FEE]
description = "The withdrawal fee"
defaultValue = "<%= parseEther('1') %>"

[provision.infinex]
options.SALT = "INFINEX_0_0_14"
options.DEPOSIT_BRIDGE_ACTIVE = "true" # This chain has no trading functionality (O2 preset)
options.OWNER = "0x33FaF56Cb2c854231bdA8De328bbAddcF76D9836"
options.REVENUE_POOL = "0x33FaF56Cb2c854231bdA8De328bbAddcF76D9836"
options.TRADING_FEE_POOL = "0x33FaF56Cb2c854231bdA8De328bbAddcF76D9836"
options.MINIMUM_BRIDGE_AMOUNT =  "<%= parseUnits(String(0.1), 6) %>"
options.USDC = "0x75faf114eafb1BDbe2F0316DF893fd58CE46AA4d"
options.CIRCLE_BRIDGE = "0x9f3B8679c73C2Fef8b59B4f3444d4e156fb70AA5"
options.CIRCLE_MINTER = "0xE997d7d2F6E065a9A93Fa2175E878Fb9081F1f0A"
options.CIRCLE_BRIDGE_DEST_DOMAIN = "6"
options.WORMHOLE_CIRCLE_BRIDGE = "0x2703483B1a5a7c577e8680de9Df8Be03c6f30e3c"
options.WORMHOLE_DESTINATION_DOMAIN_BASE = "10004"
# Non Functional parameters - functionality not on this chain
options.MAKER_FEE = "1"
options.TAKER_FEE = "1"
source = "infinex:0.0.13@O2"

# ---------- Setting Post deployment parameters  ---------- #

[invoke.setInfinexProtocolConfigBeaconFee]
target = ["infinex.InfinexProtocolConfigBeacon"]
func = "setWithdrawalFee"
args = [ "<%= settings.WITHDRAWAL_FEE %>"]
from = "<%= settings.OWNER %>"
depends = ["provision.infinex"]


[invoke.AccountFactoryInitialize]
target = ["infinex.AccountFactory"]
func = "initialize"
args = [
    "<%= imports.infinex.contracts.InfinexProtocolConfigBeacon.address %>",
    "<%= imports.infinex.contracts.InfinexProtocolConfigBeacon.address %>",
]
depends = ["provision.infinex"]
from = "<%= settings.OWNER %>"
