name = "infinex-multichain"
version = "0.0.13"
preset = "N2O"
description = "Infinex MultiChain Deployments"
#  pnpm cannon build infinex-multichain/testnets/infinex-multichain-base-sepolia.toml --chain-id 84532

[setting.OWNER]
defaultValue = "0x33FaF56Cb2c854231bdA8De328bbAddcF76D9836"
description = "The Council multisig"
 
[setting.WITHDRAWAL_FEE]
description = "The withdrawal fee"
defaultValue = "<%= parseEther('1') %>"

[setting.MAKER_FEE]
description = "The default maker fee"
defaultValue = "<%= parseEther('0.0002') %>"

[setting.TAKER_FEE]
description = "The default taker fee"
defaultValue = "<%= parseEther('0.0005') %>"

[setting.GAS_FEE_REBATE]
description = "The gas fee rebate"
defaultValue = "<%= parseUnits(String(1), 18) %>"

# This is used for trading fees
[setting.ETH_PERPS_MARKET_ID]
description = "The market ID of the ETH Perps market"
defaultValue = "100"

[setting.BTC_PERPS_MARKET_ID]
description = "The market ID of the BTC Perps market"
defaultValue = "200"


[provision.infinex]
options.SALT = "INFINEX_0_0_13"
options.DEPOSIT_BRIDGE_ACTIVE = "false"
options.OWNER = "0x33FaF56Cb2c854231bdA8De328bbAddcF76D9836"
options.REVENUE_POOL = "0x33FaF56Cb2c854231bdA8De328bbAddcF76D9836"
options.TRADING_FEE_POOL = "0x33FaF56Cb2c854231bdA8De328bbAddcF76D9836"
options.MINIMUM_BRIDGE_AMOUNT =  "<%= parseUnits(String(1), 6) %>"
options.USDC = "0x036CbD53842c5426634e7929541eC2318f3dCF7e" # Actual USDC
# options.USDC = "0x69980C3296416820623b3e3b30703A74e2320bC8" # SNX fUSDC required for trading
options.CIRCLE_BRIDGE = "0x9f3B8679c73C2Fef8b59B4f3444d4e156fb70AA5"
options.CIRCLE_MINTER = "0xE997d7d2F6E065a9A93Fa2175E878Fb9081F1f0A"
options.CIRCLE_BRIDGE_DEST_DOMAIN = "0"
options.WORMHOLE_CIRCLE_BRIDGE = "0x2703483B1a5a7c577e8680de9Df8Be03c6f30e3c"
options.WORMHOLE_DESTINATION_DOMAIN_ETHEREUM = "10002"
source = "infinex:0.0.12@N2O"


# ---------- Setting Post deployment parameters  ---------- #

[invoke.setInfinexProtocolConfigBeaconFee]
target = ["infinex.InfinexProtocolConfigBeacon"]
func = "setFeeConfiguration"
args = [     [
        { marketId = "<%= settings.ETH_PERPS_MARKET_ID %>", makerFee = "<%= settings.MAKER_FEE %>", takerFee = "<%= settings.TAKER_FEE %>" },
        { marketId = "<%= settings.BTC_PERPS_MARKET_ID %>", makerFee = "<%= settings.MAKER_FEE %>", takerFee = "<%= settings.TAKER_FEE %>" },
    ],
    "<%= settings.WITHDRAWAL_FEE %>",
    ]
from = "<%= settings.OWNER %>"


[invoke.AccountFactoryInitialize]
target = ["infinex.AccountFactory"]
func = "initialize"
args = [
    "<%= imports.infinex.contracts.InfinexProtocolConfigBeacon.address %>",
    "<%= imports.infinex.contracts.SynthetixInformationBeacon.address %>",
]
from = "<%= settings.OWNER %>"

[invoke.setInfinexProtocolConfigBeaconGasFee]
target = ["infinex.InfinexProtocolConfigBeacon"]
func = "setDefaultGasFeeRebate"
args = ["<%= settings.GAS_FEE_REBATE %>"]
from = "<%= settings.OWNER %>"