name = "infinex-multichain"
version = "0.0.5"
preset = "O2"
description = "Infinex MultiChain Deployments"


[provision.infinex]
options.SALT = "INFINEX_0_0_5_1"
options.ACCOUNT_TYPE = "0" # This chain has no trading functionality (O2 preset)
options.OWNER = "0xa7DB9b0a95D253022068d43BD1d64756f92eF83C"
options.REVENUE_POOL = "0xa7DB9b0a95D253022068d43BD1d64756f92eF83C"
options.TRADING_FEE_POOL = "0xa7DB9b0a95D253022068d43BD1d64756f92eF83C"
options.MINIMUM_BRIDGE_AMOUNT =  "<%= parseUnits(String(10), 1) %>"
options.USDC = "0x75faf114eafb1BDbe2F0316DF893fd58CE46AA4d"
options.CIRCLE_BRIDGE = "0x9f3B8679c73C2Fef8b59B4f3444d4e156fb70AA5"
options.CIRCLE_BRIDGE_DEST_DOMAIN = "6"
options.WORMHOLE_CIRCLE_BRIDGE = "0x2703483B1a5a7c577e8680de9Df8Be03c6f30e3c"
options.WORMHOLE_DESTINATION_DOMAIN_BASE = "10004"
# Non Functional parameters - functionality not on this chain
options.MAKER_FEE = "1"
options.TAKER_FEE = "1"
source = "infinex:latest@O2"
