name = "infinex-multichain"
version = "0.1.0"
preset = "O2"
description = "Infinex MultiChain Deployments"
# --chain-id 11155420 

[setting.OWNER]
defaultValue = "0x33FaF56Cb2c854231bdA8De328bbAddcF76D9836"
description = "The Council multisig"

[setting.WITHDRAWAL_FEE_USDC]
description = "The withdrawal fee in USDC"
defaultValue = "<%= parseUnits(String(1), 6) %>"

[setting.ETHEREUM_CHAIN_ID_SEPOLIA]
description = "Chain Id for Ethereum Sepolia"
type = "number"
defaultValue = "11155111"

[setting.AVALANCHE_CHAIN_ID_FUJI]
description = "Chain Id for Avalanche"
type = "number"
defaultValue = "43113"

[setting.OPTIMISM_CHAIN_ID_SEPOLIA]
description = "Chain Id for Optimism Sepolia"
type = "number"
defaultValue = "11155420"

[setting.ARBITRUM_CHAIN_ID_SEPOLIA]
description = "Chain Id for Arbitrum Sepolia"
type = "number"
defaultValue = "421614"

[setting.BASE_CHAIN_ID_SEPOLIA]
description = "Chain Id for Ethereum"
type = "number"
defaultValue = "84532"

[setting.POLYGON_CHAIN_ID_MUMBAI]
description = "Chain Id for Ethereum"
type = "number"
defaultValue = "80001"

[setting.SOLANA_CHAIN_ID_DEV]
description = "Chain Id for Ethereum"
type = "number"
defaultValue = "1"

[setting.WORMHOLE_DESTINATION_DOMAIN_ETHEREUM_SEPOLIA]
desctiption = "The Wormhole destination domain of the target chain, Optimism"
type="number"
defaultValue = "10002"

[setting.WORMHOLE_DESTINATION_DOMAIN_OPTIMISM_SEPOLIA]
desctiption = "The Wormhole destination domain of the target chain, Optimism sepolia"
type="number"
defaultValue = "10005"

[setting.WORMHOLE_DESTINATION_DOMAIN_ARBITRUM_SEPOLIA]
desctiption = "The Wormhole destination domain of the target chain, Arbitrum sepolia"
type="number"
defaultValue = "10003"

[setting.WORMHOLE_DESTINATION_DOMAIN_BASE_SEPOLIA]
desctiption = "The Wormhole destination domain of the target chain, Base Sepolia"
type="number"
defaultValue = "10004"

[setting.WORMHOLE_DESTINATION_DOMAIN_POLYGON_MUMBAI]
desctiption = "The Wormhole destination domain of the target chain, Polygon sepolia"
type="number"
defaultValue = "10007"


[provision.infinex]
options.SALT = "INFINEX_0_1_0"
options.OWNER = "0x33FaF56Cb2c854231bdA8De328bbAddcF76D9836"
options.REVENUE_POOL = "0x33FaF56Cb2c854231bdA8De328bbAddcF76D9836"
options.MINIMUM_BRIDGE_AMOUNT =  "<%= parseUnits(String(0.1), 6) %>"
options.USDC = "0x5fd84259d66Cd46123540766Be93DFE6D43130D7"
options.CIRCLE_BRIDGE = "0x9f3B8679c73C2Fef8b59B4f3444d4e156fb70AA5"
options.CIRCLE_MINTER = "0xE997d7d2F6E065a9A93Fa2175E878Fb9081F1f0A"
options.CIRCLE_BRIDGE_DEFAULT_DESTINATION_DOMAIN = "6"
options.WORMHOLE_CIRCLE_BRIDGE = "0x2703483B1a5a7c577e8680de9Df8Be03c6f30e3c"
options.WORMHOLE_DEFAULT_DESTINATION_DOMAIN = "10004"
source = "infinex:0.1.0@O2"

# ---------- Setting Post deployment parameters  ---------- #

[invoke.setInfinexProtocolConfigBeaconFee]
target = ["infinex.InfinexProtocolConfigBeacon"]
func = "setWithdrawalFeeUSDC"
args = [ "<%= settings.WITHDRAWAL_FEE_USDC %>"]
from = "<%= settings.OWNER %>"
depends = ["provision.infinex"]


[invoke.AccountFactoryInitialize]
target = ["infinex.AccountFactory"]
func = "initialize"
args = [
    "<%= imports.infinex.contracts.InfinexProtocolConfigBeacon.address %>"
]
depends = ["provision.infinex"]
from = "<%= settings.OWNER %>"

[invoke.setValidChainIdsBatchTestnetEVM]
target = ["infinex.InfinexProtocolConfigBeacon"]
func = "setIsValidChainIdsBatch"
args = [["<%= settings.ETHEREUM_CHAIN_ID_SEPOLIA %>","<%= settings.AVALANCHE_CHAIN_ID_FUJI %>", "<%= settings.OPTIMISM_CHAIN_ID_SEPOLIA %>", "<%= settings.ARBITRUM_CHAIN_ID_SEPOLIA %>", "<%= settings.BASE_CHAIN_ID_SEPOLIA %>", "<%= settings.POLYGON_CHAIN_ID_MUMBAI %>"],true,true]
from = "<%= settings.OWNER %>"

[invoke.setWormholeDestinationDomainBatchTestnetEVM]
target = ["infinex.InfinexProtocolConfigBeacon"]
func = "setWormholeDestinationDomainsBatch"
args = [["<%= settings.ETHEREUM_CHAIN_ID_SEPOLIA %>","<%= settings.AVALANCHE_CHAIN_ID_FUJI %>", "<%= settings.OPTIMISM_CHAIN_ID_SEPOLIA %>", "<%= settings.ARBITRUM_CHAIN_ID_SEPOLIA %>", "<%= settings.BASE_CHAIN_ID_SEPOLIA %>", "<%= settings.POLYGON_CHAIN_ID_MUMBAI %>"], ["<%= settings.WORMHOLE_DESTINATION_DOMAIN_ETHEREUM_SEPOLIA %>","<%= settings.WORMHOLE_DESTINATION_DOMAIN_AVALANCHE %>", "<%= settings.WORMHOLE_DESTINATION_DOMAIN_OPTIMISM_SEPOLIA %>", "<%= settings.WORMHOLE_DESTINATION_DOMAIN_ARBITRUM_SEPOLIA %>", "<%= settings.WORMHOLE_DESTINATION_DOMAIN_BASE_SEPOLIA %>","<%= settings.WORMHOLE_DESTINATION_DOMAIN_POLYGON_MUMBAI %>" ]]
from = "<%= settings.OWNER %>"

[invoke.setCircleDestinationDomainsBatchTestnetEVM]
target = ["infinex.InfinexProtocolConfigBeacon"]
func = "setCircleDestinationDomainsBatch"
args = [["<%= settings.ETHEREUM_CHAIN_ID_SEPOLIA %>","<%= settings.AVALANCHE_CHAIN_ID_FUJI %>", "<%= settings.OPTIMISM_CHAIN_ID_SEPOLIA %>", "<%= settings.ARBITRUM_CHAIN_ID_SEPOLIA %>", "<%= settings.BASE_CHAIN_ID_SEPOLIA %>", "<%= settings.POLYGON_CHAIN_ID_MUMBAI %>"], ["<%= settings.CIRCLE_DESTINATION_DOMAIN_ETHEREUM %>","<%= settings.CIRCLE_DESTINATION_DOMAIN_AVALANCHE %>", "<%= settings.CIRCLE_DESTINATION_DOMAIN_OPTIMISM %>", "<%= settings.CIRCLE_DESTINATION_DOMAIN_ARBITRUM %>", "<%= settings.CIRCLE_DESTINATION_DOMAIN_BASE %>","<%= settings.CIRCLE_DESTINATION_DOMAIN_POLYGON %>" ]]
from = "<%= settings.OWNER %>"